workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic  # Optional: for App Store
    environment:
      flutter: stable
      ios_signing:
        distribution_type: development  # No signing for .app file
      vars:
        BUNDLE_ID: "com.example.frontend"  # Replace with your bundle ID
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build
        script: |
          flutter build ios --no-codesign --simulator --debug
    artifacts:
      - build/ios/iphonesimulator/*.app
    publishing:
      # No publishing needed for testing